In [2]:
from utils.imdbmovie import get_movies
import pandas as pd
from collections import Counter

In [3]:
index_df = pd.read_csv("/data/sbaruah/movie/files/reindex.csv", index_col=None)

In [4]:
index_df.head(5)

,id,imdb_id,csm_id,title,demographics,parsed,folder,year,box_office
0,2,21884.0,NaN,frankenstein_1994,False,True,/data/sbaruah/movie/files/2/,1931.0,NaN
1,3,22054.0,NaN,last_flight_the,False,True,/data/sbaruah/movie/files/3/,1931.0,NaN
2,4,22268.0,NaN,platinum_blonde,False,True,/data/sbaruah/movie/files/4/,1931.0,NaN
3,5,22626.0,NaN,american_madness,False,True,/data/sbaruah/movie/files/5/,1932.0,NaN
4,6,22958.0,NaN,grand_hotel,True,True,/data/sbaruah/movie/files/6/,1932.0,NaN

In [5]:
index_df.parsed.sum()

1163

In [13]:
imdb_ids = index_df.imdb_id.dropna().astype(int).unique()

In [14]:
imdb_ids

array([  21884,   22054,   22268, ..., 7286456, 7349662, 1905041])

In [15]:
movie_data = get_movies(imdb_ids)

In [16]:
len(movie_data)

1183

In [18]:
movie_data["7286456"]["genres"]

['Crime', 'Drama', 'Thriller']

In [32]:
movie_data["7286456"]["rating"]

8.5

In [33]:
genres_col = []
rating_col = []

for _, row in index_df.iterrows():
    genres = None
    rating = None
    try:
        imdb_id = str(int(row.imdb_id)).zfill(7)
        genres = movie_data[imdb_id]["genres"]
    except Exception:
        pass
    try:
        imdb_id = str(int(row.imdb_id)).zfill(7)
        rating = movie_data[imdb_id]["rating"]
    except Exception:
        pass
    genres_col.append(genres)
    rating_col.append(rating)

index_df["genres"] = genres_col
index_df["rating"] = rating_col

In [39]:
for _, row in index_df[index_df.parsed].iterrows():
    if pd.notna(row.imdb_id):
        url = f"https://www.imdb.com/title/tt{str(int(row.imdb_id)).zfill(7)}/"
        if row.rating > 8:
            print(row.id, url, row.year, row.title, row.rating, row.genres)

8 https://www.imdb.com/title/tt0025316/ 1934.0 it_happened_one_night 8.1 ['Comedy', 'Romance']
13 https://www.imdb.com/title/tt0031679/ 1939.0 mr._smith_goes_to_washington 8.1 ['Comedy', 'Drama']
20 https://www.imdb.com/title/tt0033467/ 1941.0 citizen_kane 8.3 ['Drama', 'Mystery']
29 https://www.imdb.com/title/tt0036112/ 1943.0 the_life_and_death_of_colonel_blimp 8.1 ['Drama', 'Romance', 'War']
33 https://www.imdb.com/title/tt0036775/ 1944.0 double_indemnity 8.3 ['Crime', 'Drama', 'Film-Noir', 'Mystery', 'Thriller']
39 https://www.imdb.com/title/tt0038650/ 1946.0 its_a_wonderful_life 8.6 ['Drama', 'Family', 'Fantasy']
49 https://www.imdb.com/title/tt0042192/ 1950.0 all_about_eve 8.2 ['Drama']
59 https://www.imdb.com/title/tt0047296/ 1954.0 on_the_waterfront 8.1 ['Crime', 'Drama', 'Thriller']
60 https://www.imdb.com/title/tt0047396/ 1954.0 rear_window 8.4 ['Mystery', 'Thriller']
72 https://www.imdb.com/title/tt0050976/ 1957.0 seventh_seal_the 8.2 ['Drama', 'Fantasy']
74 https://www.imdb.com/title/tt0051036/ 1957.0 sweet_smell_of_success 8.1 ['Drama', 'Film-Noir']
76 https://www.imdb.com/title/tt0052357/ 1958.0 vertigo 8.3 ['Mystery', 'Romance', 'Thriller']
79 https://www.imdb.com/title/tt0053291/ 1959.0 some_like_it_hot 8.2 ['Comedy', 'Music', 'Romance']
80 https://www.imdb.com/title/tt0053604/ 1960.0 apartment_the 8.3 ['Comedy', 'Drama', 'Romance']
86 https://www.imdb.com/title/tt0056241/ 1962.0 miracle_worker_the 8.1 ['Biography', 'Drama']
94 https://www.imdb.com/title/tt0058946/ 1966.0 battle_of_algiers_the 8.1 ['Drama', 'War']
100 https://www.imdb.com/title/tt0062622/ 1968.0 2001_a_space_odyssey 8.3 ['Adventure', 'Sci-Fi']
121 https://www.imdb.com/title/tt0068646/ 1972.0 godfather 9.2 ['Crime', 'Drama']
127 https://www.imdb.com/title/tt0070735/ 1973.0 sting_the 8.3 ['Comedy', 'Crime', 'Drama']
129 https://www.imdb.com/title/tt0071315/ 1974.0 chinatown 8.2 ['Drama', 'Mystery', 'Thriller']
130 https://www.imdb.com/title/tt0071562/ 1974.0 godfather_part_ii 9.0 ['Crime', 'Drama']
132 https://www.imdb.com/title/tt0072684/ 1975.0 barry_lyndon 8.1 ['Adventure', 'Drama', 'History', 'War']
137 https://www.imdb.com/title/tt0073486/ 1975.0 one_flew_over_the_cuckoos_nest 8.7 ['Drama']
146 https://www.imdb.com/title/tt0075148/ 1976.0 rocky 8.1 ['Drama', 'Sport']
147 https://www.imdb.com/title/tt0075314/ 1976.0 taxi_driver 8.3 ['Crime', 'Drama']
151 https://www.imdb.com/title/tt0076759/ 1977.0 star_wars_a_new_hope 8.6 ['Action', 'Adventure', 'Fantasy', 'Sci-Fi']
154 https://www.imdb.com/title/tt0077416/ 1978.0 deer_hunter_the 8.1 ['Drama', 'War']
158 https://www.imdb.com/title/tt0078788/ 1979.0 apocalypse_now 8.4 ['Drama', 'Mystery', 'War']
168 https://www.imdb.com/title/tt0080678/ 1980.0 elephant_man_the 8.1 ['Biography', 'Drama']
169 https://www.imdb.com/title/tt0080684/ 1980.0 star_wars_the_empire_strikes_back 8.7 ['Action', 'Adventure', 'Fantasy', 'Sci-Fi']
174 https://www.imdb.com/title/tt0081398/ 1980.0 raging_bull 8.2 ['Biography', 'Drama', 'Sport']
175 https://www.imdb.com/title/tt0081505/ 1980.0 shining_the 8.4 ['Drama', 'Horror']
186 https://www.imdb.com/title/tt0082971/ 1981.0 indiana_jones_and_the_raiders_of_the_lost_ark 8.4 ['Action', 'Adventure']
190 https://www.imdb.com/title/tt0083658/ 1982.0 blade_runner 8.1 ['Action', 'Sci-Fi', 'Thriller']
200 https://www.imdb.com/title/tt0084787/ 1982.0 thing_the 8.1 ['Horror', 'Mystery', 'Sci-Fi']
207 https://www.imdb.com/title/tt0086190/ 1983.0 star_wars_return_of_the_jedi 8.3 ['Action', 'Adventure', 'Fantasy', 'Sci-Fi']
208 https://www.imdb.com/title/tt0086250/ 1983.0 scarface 8.3 ['Crime', 'Drama']
212 https://www.imdb.com/title/tt0086879/ 1984.0 amadeus 8.3 ['Biography', 'Drama', 'History', 'Music']
244 https://www.imdb.com/title/tt0090605/ 1986.0 aliens 8.3 ['Action', 'Adventure', 'Sci-Fi', 'Thriller']
253 https://www.imdb.com/title/tt0091763/ 1986.0 platoon 8.1 ['Drama', 'War']
265 https://www.imdb.com/title/tt0093779/ 1987.0 princess_bride_the 8.1 ['Adventure', 'Family', 'Fantasy', 'Romance']
280 https://www.imdb.com/title/tt0095016/ 1988.0 die_hard 8.2 ['Action', 'Thriller']
285 https://www.imdb.com/title/tt0095765/ 1988.0 cinema_paradiso 8.5 ['Drama']
294 https://www.imdb.com/title/tt0097165/ 1989.0 dead_poets_society 8.1 ['Comedy', 'Drama']
304 https://www.imdb.com/title/tt0097576/ 1989.0 indiana_jones_and_the_last_crusade 8.2 ['Action', 'Adventure']
323 https://www.imdb.com/title/tt0099685/ 1990.0 good_fellas 8.7 ['Biography', 'Crime', 'Drama']
356 https://www.imdb.com/title/tt0102926/ 1991.0 silence_of_the_lambs 8.6 ['Crime', 'Drama', 'Thriller']
357 https://www.imdb.com/title/tt0103064/ 1991.0 terminator_2_judgement_day 8.5 ['Action', 'Sci-Fi']
385 https://www.imdb.com/title/tt0105236/ 1992.0 reservoir_dogs 8.3 ['Crime', 'Drama', 'Thriller']
391 https://www.imdb.com/title/tt0105695/ 1992.0 unforgiven 8.2 ['Drama', 'Western']
405 https://www.imdb.com/title/tt0107290/ 1993.0 jurassic_park 8.1 ['Action', 'Adventure', 'Sci-Fi', 'Thriller']
414 https://www.imdb.com/title/tt0108052/ 1993.0 schindlers_list 8.9 ['Biography', 'Drama', 'History']
431 https://www.imdb.com/title/tt0109830/ 1994.0 forrest_gump 8.8 ['Drama', 'Romance']
444 https://www.imdb.com/title/tt0110912/ 1994.0 pulp_fiction 8.9 ['Crime', 'Drama']
447 https://www.imdb.com/title/tt0111161/ 1994.0 shawshank_redemption_the 9.3 ['Drama']
455 https://www.imdb.com/title/tt0112573/ 1995.0 braveheart 8.3 ['Biography', 'Drama', 'History', 'War']
456 https://www.imdb.com/title/tt0112641/ 1995.0 casino 8.2 ['Crime', 'Drama']
464 https://www.imdb.com/title/tt0113277/ 1995.0 heat 8.2 ['Crime', 'Drama', 'Thriller']
477 https://www.imdb.com/title/tt0114369/ 1995.0 se7en 8.6 ['Crime', 'Drama', 'Mystery', 'Thriller']
481 https://www.imdb.com/title/tt0114709/ 1995.0 toy_story 8.3 ['Animation', 'Adventure', 'Comedy', 'Family', 'Fantasy']
483 https://www.imdb.com/title/tt0114814/ 1995.0 the_usual_suspects 8.5 ['Crime', 'Mystery', 'Thriller']
498 https://www.imdb.com/title/tt0116282/ 1996.0 fargo 8.1 ['Crime', 'Drama', 'Thriller']
515 https://www.imdb.com/title/tt0117951/ 1996.0 trainspotting 8.1 ['Drama']
529 https://www.imdb.com/title/tt0118715/ 1998.0 big_lebowski_the 8.1 ['Comedy', 'Crime', 'Sport']
546 https://www.imdb.com/title/tt0119217/ 1997.0 good_will_hunting 8.3 ['Drama', 'Romance']
554 https://www.imdb.com/title/tt0119488/ 1997.0 l.a._confidential 8.2 ['Crime', 'Drama', 'Mystery', 'Thriller']
575 https://www.imdb.com/title/tt0120382/ 1998.0 the_truman_show 8.1 ['Comedy', 'Drama', 'Sci-Fi']
577 https://www.imdb.com/title/tt0120586/ 1998.0 american_history_x 8.5 ['Drama']
591 https://www.imdb.com/title/tt0120689/ 1999.0 green_mile_the 8.6 ['Crime', 'Drama', 'Fantasy', 'Mystery']
593 https://www.imdb.com/title/tt0120735/ 1998.0 lock_stock_and_two_smoking_barrels 8.2 ['Action', 'Comedy', 'Crime']
594 https://www.imdb.com/title/tt0120737/ 2001.0 lord_of_the_rings_fellowship_of_the_ring_the 8.8 ['Action', 'Adventure', 'Drama', 'Fantasy']
605 https://www.imdb.com/title/tt0120815/ 1998.0 saving_private_ryan 8.6 ['Drama', 'War']
638 https://www.imdb.com/title/tt0133093/ 1999.0 matrix_the 8.7 ['Action', 'Sci-Fi']
646 https://www.imdb.com/title/tt0137523/ 1999.0 fight_club 8.8 ['Drama']
695 https://www.imdb.com/title/tt0167260/ 2003.0 lord_of_the_rings_return_of_the_king 8.9 ['Adventure', 'Drama', 'Fantasy']
696 https://www.imdb.com/title/tt0167261/ 2002.0 lord_of_the_rings_the_two_towers 8.7 ['Adventure', 'Drama', 'Fantasy']
697 https://www.imdb.com/title/tt0167404/ 1999.0 sixth_sense_the 8.1 ['Drama', 'Mystery', 'Thriller']
702 https://www.imdb.com/title/tt0172495/ 2000.0 gladiator 8.5 ['Action', 'Adventure', 'Drama']
745 https://www.imdb.com/title/tt0209144/ 2000.0 memento 8.4 ['Mystery', 'Thriller']
786 https://www.imdb.com/title/tt0253474/ 2002.0 pianist_the 8.5 ['Biography', 'Drama', 'Music', 'War']
800 https://www.imdb.com/title/tt0264464/ 2002.0 catch_me_if_you_can 8.1 ['Biography', 'Crime', 'Drama']
803 https://www.imdb.com/title/tt0266543/ 2003.0 finding_nemo 8.1 ['Animation', 'Adventure', 'Comedy', 'Family']
804 https://www.imdb.com/title/tt0266697/ 2003.0 kill_bill_volume_1_and_2 8.1 ['Action', 'Crime', 'Thriller']
868 https://www.imdb.com/title/tt0338013/ 2004.0 eternal_sunshine_of_the_spotless_mind 8.3 ['Drama', 'Romance', 'Sci-Fi']
882 https://www.imdb.com/title/tt0361748/ 2009.0 inglourious_basterds 8.3 ['Adventure', 'Drama', 'War']
921 https://www.imdb.com/title/tt0395169/ 2004.0 hotel_rwanda 8.1 ['Biography', 'Drama', 'History', 'War']
939 https://www.imdb.com/title/tt0407887/ 2006.0 departed_the 8.5 ['Crime', 'Drama', 'Thriller']
974 https://www.imdb.com/title/tt0434409/ 2005.0 v_for_vendetta 8.2 ['Action', 'Drama', 'Sci-Fi', 'Thriller']
1013 https://www.imdb.com/title/tt0477348/ 2007.0 no_country_for_old_men 8.1 ['Crime', 'Drama', 'Thriller']
1022 https://www.imdb.com/title/tt0482571/ 2006.0 prestige_the 8.5 ['Drama', 'Mystery', 'Sci-Fi', 'Thriller']
1032 https://www.imdb.com/title/tt0758758/ 2007.0 into_the_wild 8.1 ['Adventure', 'Biography', 'Drama']
1054 https://www.imdb.com/title/tt0816692/ 2014.0 interstellar 8.6 ['Adventure', 'Drama', 'Sci-Fi', 'Thriller']
1079 https://www.imdb.com/title/tt0892769/ 2010.0 how_to_train_your_dragon 8.1 ['Animation', 'Action', 'Adventure', 'Family', 'Fantasy']
1084 https://www.imdb.com/title/tt0910970/ 2008.0 walle 8.4 ['Animation', 'Adventure', 'Family', 'Sci-Fi']
1106 https://www.imdb.com/title/tt0993846/ 2013.0 wolf_of_wall_street_the 8.2 ['Biography', 'Crime', 'Drama']
1131 https://www.imdb.com/title/tt1049413/ 2009.0 up 8.2 ['Animation', 'Adventure', 'Comedy', 'Family']
1174 https://www.imdb.com/title/tt1205489/ 2008.0 gran_torino 8.1 ['Drama']
1200 https://www.imdb.com/title/tt1291584/ 2011.0 warrior 8.2 ['Action', 'Drama', 'Sport']
1210 https://www.imdb.com/title/tt1345836/ 2012.0 dark_knight_rises_the 8.4 ['Action', 'Adventure']
1214 https://www.imdb.com/title/tt1375666/ 2010.0 inception 8.8 ['Action', 'Adventure', 'Sci-Fi', 'Thriller']
1231 https://www.imdb.com/title/tt1454029/ 2011.0 help_the 8.1 ['Drama']
1289 https://www.imdb.com/title/tt1853728/ 2012.0 django_unchained 8.4 ['Drama', 'Western']
1294 https://www.imdb.com/title/tt1979320/ 2013.0 rush 8.1 ['Biography', 'Drama', 'Sport']
1296 https://www.imdb.com/title/tt2024544/ 2013.0 12_years_a_slave 8.1 ['Biography', 'Drama', 'History']
1313 https://www.imdb.com/title/tt2380307/ 2017.0 coco 8.4 ['Animation', 'Adventure', 'Family', 'Fantasy', 'Music', 'Mystery']
1326 https://www.imdb.com/title/tt3170832/ 2015.0 room 8.1 ['Drama', 'Thriller']
1328 https://www.imdb.com/title/tt3315342/ 2017.0 logan 8.1 ['Action', 'Drama', 'Sci-Fi', 'Thriller']
1341 https://www.imdb.com/title/tt7286456/ 2019.0 joker 8.5 ['Crime', 'Drama', 'Thriller']

In [41]:
index_df[index_df.imdb_id.isin([7286456,6644200,4154796,3397884,2948356,2911666,97165,75148,120689,988045,1570728,120815,108052,110912,102926,266543,114814,482571,816692,1375666])]

,id,imdb_id,csm_id,title,demographics,parsed,folder,year,box_office,genres,rating
109,146,75148.0,fc129826-544e-4c58-858b-dd49ddad9f47,rocky,True,True,/data/sbaruah/movie/files/146/,1976.0,5000000.0,"[Drama, Sport]",8.1
237,294,97165.0,2852bd7a-b874-404f-a6e9-ae819a702fca,dead_poets_society,True,True,/data/sbaruah/movie/files/294/,1989.0,340456.0,"[Comedy, Drama]",8.1
291,356,102926.0,20c373f6-52cf-4e4f-a779-622854cc534c,silence_of_the_lambs,True,True,/data/sbaruah/movie/files/356/,1991.0,13766814.0,"[Crime, Drama, Thriller]",8.6
345,414,108052.0,be524081-1b93-48f1-8c3f-ac231e53c2b2,schindlers_list,True,True,/data/sbaruah/movie/files/414/,1993.0,566760.0,"[Biography, Drama, History]",8.9
371,444,110912.0,d2307626-4ae9-4524-a65e-46a013cfd7b3,pulp_fiction,True,True,/data/sbaruah/movie/files/444/,1994.0,9311882.0,"[Crime, Drama]",8.9
404,483,114814.0,9e1c0d67-7945-4e51-ad66-509652797d1b,the_usual_suspects,True,True,/data/sbaruah/movie/files/483/,1995.0,645363.0,"[Crime, Mystery, Thriller]",8.5
507,591,120689.0,3c707130-7601-477b-b2b9-552d6978634e,green_mile_the,True,True,/data/sbaruah/movie/files/591/,1999.0,18017152.0,"[Crime, Drama, Fantasy, Mystery]",8.6
521,605,120815.0,d5cbd279-f6fb-44c3-9541-e38e7ccf3b08,saving_private_ryan,True,True,/data/sbaruah/movie/files/605/,1998.0,30576104.0,"[Drama, War]",8.6
704,803,266543.0,https://www.commonsensemedia.org/movie-reviews...,finding_nemo,True,True,/data/sbaruah/movie/files/803/,2003.0,16687773.0,"[Animation, Adventure, Comedy, Family]",8.1
870,1022,482571.0,NaN,prestige_the,False,True,/data/sbaruah/movie/files/1022/,2006.0,NaN,"[Drama, Mystery, Sci-Fi, Thriller]",8.5
898,1054,816692.0,bc79a260-b455-4c14-bdb8-91a06478b7c7,interstellar,True,True,/data/sbaruah/movie/files/1054/,2014.0,47510360.0,"[Adventure, Drama, Sci-Fi, Thriller]",8.6
943,1103,988045.0,b6856c75-5e98-4fb7-92a6-256f2d35c8a3,sherlock_holmes,True,True,/data/sbaruah/movie/files/1103/,2009.0,62304277.0,"[Action, Adventure, Mystery]",7.6
1054,1214,1375666.0,3043640c-0c61-472f-9912-07464a04a8c5,inception,True,True,/data/sbaruah/movie/files/1214/,2010.0,62785337.0,"[Action, Adventure, Sci-Fi, Thriller]",8.8
1095,1255,1570728.0,https://www.commonsensemedia.org/movie-reviews...,crazy_stupid_love,True,True,/data/sbaruah/movie/files/1255/,2011.0,19104303.0,"[Comedy, Drama, Romance]",7.4
1162,1322,2911666.0,NaN,john_wick,False,True,/data/sbaruah/movie/files/1322/,2014.0,14415922.0,"[Action, Crime, Thriller]",7.4
1164,1324,2948356.0,NaN,zootopia,False,True,/data/sbaruah/movie/files/1324/,2016.0,75063401.0,"[Animation, Adventure, Comedy, Crime, Family, ...",8.0
1169,1329,3397884.0,NaN,sicario,False,True,/data/sbaruah/movie/files/1329/,2015.0,12148041.0,"[Action, Crime, Drama, Mystery, Thriller]",7.6
1179,1340,6644200.0,NaN,a_quiet_place,False,True,/data/sbaruah/movie/files/1340/,2018.0,50203562.0,"[Drama, Horror, Sci-Fi]",7.5
1180,1341,7286456.0,NaN,joker,False,True,/data/sbaruah/movie/files/1341/,2019.0,96202337.0,"[Crime, Drama, Thriller]",8.5

In [44]:
"7286456,6644200,4154796,3397884,2948356,2911666,97165,75148,120689,988045,1570728,120815,108052,110912,102926,266543,114814,482571,816692,1375666".replace(",", " ")

'7286456 6644200 4154796 3397884 2948356 2911666 97165 75148 120689 988045 1570728 120815 108052 110912 102926 266543 114814 482571 816692 1375666'

In [47]:
" ".join(index_df[index_df.imdb_id.isin([7286456,6644200,4154796,3397884,2948356,2911666,97165,75148,120689,988045,1570728,120815,108052,110912,102926,266543,114814,482571,816692,1375666])].id.values.astype(str))

'146 294 356 414 444 483 591 605 803 1022 1054 1103 1214 1255 1322 1324 1329 1340 1341'